const CONFIG = {
  allItems: [
"8-bit Power-Up Potion",
"A Chia Halloween",
"A Chia Story",
"A History of Chias",
"A Plague Upon You!",
"A Seasonal Pea",
"Aboogala",
"Acara Ear Guards",
"Acara Gladiator Boots",
"Acara Twin Blade",
"Advanced Poetry",
"Air Faerie Doll",
"Air Faerie Token",
"Aisha Acorn Darts",
"Aisha Feathered Charm",
"Alchemy Lessons",
"Alien Aisha Invasion",
"Alien Usuki",
"All About Dark Faeries",
"All About Fire Faeries",
"All Seeing Tree",
"Altadorian Crest Buckler",
"Amulet of the Unblinking Eye",
"Angelic Ice Lolly",
"Animal-style Chips",
"Apple Jelly Club",
"Apple Lantern",
"Apple Moquot Lollypop",
"Archmagus of Roo Plushie",
"ARGH!!!! DONNA STAMP",
"Aromatic Candle",
"Artichoke and Onion Surprise",
"Artichoke Cupcake",
"Artichoke Fondue",
"Asparagus Balls",
"Asparagus Garden",
"Asparagus Pen",
"Asparagus Pie",
"Babith",
"Baby Acara Morphing Potion",
"Baby Aisha Morphing Potion",
"Baby Bruce Morphing Potion",
"Baby Buzz Morphing Potion",
"Baby Chia Morphing Potion",
"Baby Chomby Morphing Potion",
"Baby Draik Morphing Potion",
"Baby Gnorbu Morphing Potion",
"Baby Hissi Morphing Potion",
"Baby Jetsam Morphing Potion",
"Baby JubJub Morphing Potion",
"Baby Kacheek Morphing Potion",
"Baby Kau Morphing Potion",
"Baby Koi Morphing Potion",
"Baby Korbat Morphing Potion",
"Baby Kougra Morphing Potion",
"Baby Lupe Morphing Potion",
"Baby Meerca Morphing Potion",
"Baby Scorchio Morphing Potion",
"Baby Uni Morphing Potion",
"Bacon Belly Buster",
"Bad Seed",
"Bag of Healing Dust",
"Bag of Lenny Healing Seeds",
"Bag of Sand",
"Ballerina Quiguki",
"Barbed Buzz Dagger",
"Bat Thing Plushie",
"Battle Hammer",
"Battle Slices Stamp",
"Beating Sloth",
"Beautiful Hair Quiguki Doll",
"Beepallite",
"Bendy Desk Light",
"Best Friends",
"Big Beefy Hot Dog",
"Big Gulp Neocola",
"Billion Degree Sword",
"Black Currant Juice",
"Black Frost Cannon",
"Black Long Sleeved Cape",
"Black Wadjet Plushie",
"Blackberry Eyrie Cookie",
"Blade of Supernova",
"Blade of the Battle Faerie",
"Blade of Ultranova",
"Blechy",
"Blizzard Kougra Plushie",
"Blobikins",
"Blood Mole Plant",
"Bloodberry Elixir",
"BLT Croissant",
"Bludberry",
"Blue Acara Bow",
"Blue Acara Morphing Potion",
"Blue Acara Slingshot",
"Blue Blumaroo Morphing Potion",
"Blue Bogie T-Shirt",
"Blue Bori Morphing Potion",
"Blue Buzz Morphing Potion",
"Blue Chia Morphing Potion",
"Blue Clockwork Grundo",
"Blue Clockwork Kiko",
"Blue Cybunny Morphing Potion",
"Blue Doglefox Plushie",
"Blue Doughnutfruit",
"Blue Draik Morphing Potion",
"Blue Gelert Morphing Potion",
"Blue Grarrl Morphing Potion",
"Blue Kacheek Morphing Potion",
"Blue Kau Morphing Potion",
"Blue Khonsu T-Shirt",
"Blue Kiko Morphing Potion",
"Blue Koi Morphing Potion",
"Blue Korbat Morphing Potion",
"Blue Kougra Morphing Potion",
"Blue Krawk Morphing Potion",
"Blue Lenny Morphing Potion",
"Blue Mynci Morphing Potion",
"Blue Nimmo Boots",
"Blue Nimmo Morphing Potion",
"Blue Peophin Morphing Potion",
"Blue Quiggle Morphing Potion",
"Blue Shoyru Morphing Potion",
"Blue Skeith Morphing Potion",
"Blue Techo Morphing Potion",
"Blue Tonu Morphing Potion",
"Blue Tuskaninny Morphing Potion",
"Blue Uni Morphing Potion",
"Blue Usul Morphing Potion",
"Blue Wocky Morphing Potion",
"Blue Zafara Morphing Potion",
"Blueberry Deluxe Cake",
"Blueberry Jelly Bass",
"Blumaroo Battle Staff",
"Blumaroo Health Potion",
"Blumaroo Pepper Shaker",
"Blumaroo Slingshot",
"Blumaroo Statue",
"Blushing Bride Quiguki Doll",
"Bogie",
"Bone Sword",
"Bone Trombone",
"Bonsai Chia",
"Bony Grarrl Club",
"Book of Flames",
"Book of Scarabs",
"Boraxis Plushie",
"Borovan Layered Cake",
"Bottle of Bubbles Sand",
"Bottled Uni Essence",
"Bouncy Kiko Ball of Doom",
"Bow of the Air Faerie",
"Bow of the Light Faerie",
"Bow of the Water Faerie",
"Bowe Plushie",
"Brain Of Mirgle",
"Brain Trees Brainiac",
"Brass Bruce Horn Of Deafening",
"Bread Wreath",
"Breebly",
"Brilliant Poogle Buckler",
"Brilliant Poogle Wand",
"Broccoli with Sprinkles",
"Bronze Gong",
"Brown Bruce Morphing Potion",
"Brown Clockwork Grundo",
"Brown Ixi Morphing Potion",
"Brown Wadjet Plushie",
"Bruce Icicle Spear",
"Bruces Guide to Combat Eating",
"Bubbling Flotsam Elixir",
"Bubbling Kraku Thickshake",
"Bubbling Lupe Potion",
"Bubbling Ruki Elixir",
"Bumbluz",
"Burning Hot Dog",
"Buttered Juppie Waffle",
"Buzz Hive Bomb",
"Bzzapper",
"C430 Autobot",
"Cadaverous Cola",
"Cadro",
"Calculation Device",
"Candy Cane Chocolate Advent Calendar",
"Candy Floss Carrot",
"Candy Vampire",
"Candychan",
"Captain Scarblade Stamp",
"Captain Xelqued",
"Care of Koi",
"Carved Watermelon",
"Cauliflower Lolly",
"Cauliflower Shake",
"Cauliflower Soup",
"Chain of Onions",
"Chaos Giant Plushie",
"Charcoal",
"Checkered Acara Morphing Potion",
"Checkered Aisha Morphing Potion",
"Checkered Doughnutfruit",
"Checkered Kiko Morphing Potion",
"Checkered Poogle Morphing Potion",
"Cheerleader Quiguki Doll",
"Cheerleader Usuki Reject",
"Cheese Chair",
"Cheese Lamp",
"Cheese Mat",
"Cheese Pillow",
"Cheeseburger Slushie",
"Cheesy Asparagus",
"Cheesy Carrots",
"Cherry Lemonade Slushie",
"Chia Apple Bomb",
"Chia Art History",
"Chia Cake",
"Chia Mites",
"Chia Ray Gun",
"Chia Statue",
"Chicken Filets with Fancy Sauce",
"Chilli Chucks",
"Chilli Sword",
"Chocolate Chip Eyrie Cookie",
"Chocolate Chip Quiggle Cookie",
"Chocolate Coated Blue Cheese",
"Chocolate Coated Cheese Strings",
"Chocolate Cream Biscuit",
"Chocolate Crown of the Faeries",
"Chocolate Moltenore",
"Chokato",
"Chokato Bean Bag",
"Chokato Deluxe Aisha Cake",
"Choker of the Deep",
"Chomby Lucky Charm Bracelet",
"Chomby Mysteries",
"Chomby Staff",
"Christmas Blumaroo Morphing Potion",
"Christmas Bori Morphing Potion",
"Christmas Bruce Morphing Potion",
"Christmas Gelert Morphing Potion",
"Christmas Grundo Morphing Potion",
"Christmas Ixi Morphing Potion",
"Christmas JubJub Morphing Potion",
"Christmas Kiko Morphing Potion",
"Christmas Koi Morphing Potion",
"Christmas Korbat Morphing Potion",
"Christmas Korbat Plushie",
"Christmas Kougra Morphing Potion",
"Christmas Magic Hat",
"Christmas Pteri Morphing Potion",
"Christmas Scorchio Morphing Potion",
"Christmas Uni Morphing Potion",
"Christmas Wocky Morphing Potion",
"Chrysolite Dervish Plushie",
"Cinnamon Eyrie Cookie",
"Claw of the Ancient Bori",
"Clay Aisha Morphing Potion",
"Cloak of Night",
"Clock",
"Clockwork Nimmo",
"Cloud Bori Morphing Potion",
"Cloud Bruce Morphing Potion",
"Cloud Charm",
"Cloud Cybunny Morphing Potion",
"Cloud Draik Plushie",
"Cloud Elephante Morphing Potion",
"Cloud Eyrie Morphing Potion",
"Cloud Grarrl Morphing Potion",
"Cloud Ixi Morphing Potion",
"Cloud Lenny Morphing Potion",
"Cloud Lenny Plushie",
"Cloud Ruki Morphing Potion",
"Cloud Scorchio Morphing Potion",
"Cloud Shoyru Morphing Potion",
"Coco Pumpkin",
"Cocoa Juppie Mocha",
"Coconut Shy Outdoor Play Set",
"Coffee Service",
"Collectors Edition Quiguki Boy Plushie",
"Coltzans Battle Sceptre",
"Combo Battle Mirror",
"Cone-Shaped Cherry",
"Cooty",
"Copper Bracelet",
"Coral Koi Slingshot",
"Cornupepper",
"Crisp Blue Tunic",
"Crunchy Snotball",
"Culture and History of Faerieland",
"Cures for Bad Breath",
"Curse of Foul Odour",
"Curse of Ultimate Malison",
"Cursed Elixir",
"Curved Glowing Drawer",
"Curved Wocky Sabre",
"Cutout Violin",
"Cybunny Care",
"Cybunny Shield",
"Cybunny Sword",
"Dargil Meat Mince Pie",
"Darigan Acara Morphing Potion",
"Darigan Acara Plushie",
"Darigan Aisha Morphing Potion",
"Darigan Blumaroo Morphing Potion",
"Darigan Bori Morphing Potion",
"Darigan Buzz Morphing Potion",
"Darigan Draik Egg",
"Darigan Draik Morphing Potion",
"Darigan Eyrie Morphing Potion",
"Darigan Globe",
"Darigan Grarrl Morphing Potion",
"Darigan Grundo Morphing Potion",
"Darigan Ixi Morphing Potion",
"Darigan Kau Morphing Potion",
"Darigan Kyrii Morphing Potion",
"Darigan Mynci Morphing Potion",
"Darigan Quiggle Morphing Potion",
"Darigan Spectre Stamp",
"Darigan Techo Morphing Potion",
"Darigan Wocky Morphing Potion",
"Darigan Zafara Morphing Potion",
"Dark Faerie Bow",
"Dark Faerie Doll",
"Dark Faerie Token",
"Dark Nova Lamp",
"Dark Nova Rug",
"Dark Nova Sofa",
"Dark Nova Table",
"Darkest Faerie Plushie",
"Dazzling Steel Lenny Wings",
"Decoding a Coded Decoding Book",
"Dehydration Potion",
"Delicate Terracotta Jug",
"Deluxe Strawberry Toffee Chokato",
"Desert Aisha Morphing Potion",
"Desert Blumaroo Morphing Potion",
"Desert Chomby Morphing Potion",
"Desert Cobrall Plushie",
"Desert Elephante Morphing Potion",
"Desert Flotsam Morphing Potion",
"Desert Ixi Morphing Potion",
"Desert Lupe Plushie",
"Desert Lutari Morphing Potion",
"Desert Mynci Morphing Potion",
"Desert Poogle Morphing Potion",
"Desert Scorchio Morphing Potion",
"Desert Yurble Morphing Potion",
"Diamond Hot Dog",
"Diet Big Gulp Neocola",
"Disco Birdhouse",
"Disco Bruce Morphing Potion",
"Disco Bruce Plushie",
"Disco Kacheek Morphing Potion",
"Disco Korbat Morphing Potion",
"Disco Moehog Morphing Potion",
"Disco Mynci Morphing Potion",
"Disco Print Bed",
"Disco Shoyru Morphing Potion",
"Ditrey",
"Double Chocolate Jelly Beans",
"Double Cream Vanilla Sponge",
"Double Printed Evil Fuzzle Stamp",
"Doughnutfruit",
"Dr Sloth Backpack",
"Draconus Maximus",
"Dragonfly Nymph",
"Draik Enhancement Brew",
"Draphly",
"Dua",
"Duel Bazuka",
"Dung Derived Lipstick",
"Dung Snowflake",
"Dusk Kougra Plushie",
"Dusty Harmless Looking Scroll",
"Dusty Magic Broom",
"Dwoobaphone",
"Earth Faerie Token",
"Edible Magenorb Bouquet",
"Egg and Tomato Sandwich",
"Electric Grarrl Morphing Potion",
"Electric Ixi Morphing Potion",
"Electric Moehog Morphing Potion",
"Electro Lizard Plushie",
"Elephante Lamp Collectable Charm",
"Eleskeleton 3000",
"Elixir of the Pirate",
"Emerald Hissi Breastplate",
"Emerald Hissi Shield",
"Emerald Krawk Boots",
"Emerald Krawk Jacket",
"Emerald Krawk Sword",
"Enchanted Ixi",
"Enchanted Ixi Wand",
"Enchanted Kiko Shield",
"Enchanted Kougra Pendant",
"Enhanced Acara Potion",
"ErgyFruit",
"Erisim T-Shirt",
"Ethereal Sword",
"Eventide Tonu Morphing Potion",
"Evil Blancmange",
"Evil Pinanna",
"Experimental Physics",
"Exploding Blumaroo Dice",
"Extreme Herder",
"Eye Of Mortog",
"Eyrie Pocket Catapult",
"Eyrie Tail Guard",
"Faerie Acara Morphing Potion",
"Faerie Birdhouse",
"Faerie Blumaroo Morphing Potion",
"Faerie Bori Morphing Potion",
"Faerie Bruce Morphing Potion",
"Faerie Chocodrop",
"Faerie Dreamwich",
"Faerie Eyrie Morphing Potion",
"Faerie Fruit Salad",
"Faerie Grundo Morphing Potion",
"Faerie Ixi Morphing Potion",
"Faerie JubJub Morphing Potion",
"Faerie Korbat Plushie",
"Faerie Krawk Morphing Potion",
"Faerie Lupe Morphing Potion",
"Faerie Meerca Morphing Potion",
"Faerie Nimmo Morphing Potion",
"Faerie Peophin Morphing Potion",
"Faerie Poogle Morphing Potion",
"Faerie Quiggle Morphing Potion",
"Faerie Ruki Morphing Potion",
"Faerie Shoyru Morphing Potion",
"Faerie Sparklecake",
"Faerie Techo Morphing Potion",
"Faerie Tuskaninny Morphing Potion",
"Faerie Usul Morphing Potion",
"Faerie Yurble Morphing Potion",
"Faleinn Plushie",
"Fancy Bottle of Sand",
"Fearsome Gladius",
"Feather Bow and Arrow",
"Feathered Bruce Helm",
"Feathered Pteri Cloak",
"Fiery Doughnutfruit",
"Fiery Spine of Death",
"Fiery Throwing Marble",
"Fiery Wand",
"Fire Acara Morphing Potion",
"Fire Ball Staff",
"Fire Blumaroo Morphing Potion",
"Fire Bori Morphing Potion",
"Fire Bruce Morphing Potion",
"Fire Buzz Morphing Potion",
"Fire Chia Morphing Potion",
"Fire Chomby Morphing Potion",
"Fire Draik Morphing Potion",
"Fire Eyrie Plushie",
"Fire Faerie Doll",
"Fire Faerie Hair Brush",
"Fire Faerie Token",
"Fire Faerie Usuki Set",
"Fire Flail",
"Fire Hammer",
"Fire Ixi Morphing Potion",
"Fire Kacheek Morphing Potion",
"Fire Kiko Morphing Potion",
"Fire Kyrii Morphing Potion",
"Fire Lizard Plushie",
"Fire Lupe Morphing Potion",
"Fire Moehog Morphing Potion",
"Fire Nimmo Morphing Potion",
"Fire Pteri Morphing Potion",
"Fire Quiggle Morphing Potion",
"Fire Ruki Morphing Potion",
"Fire Shoyru Morphing Potion",
"Fire Skeith Morphing Potion",
"Fire Techo Morphing Potion",
"Fire Tuskaninny Morphing Potion",
"Fire Wocky Morphing Potion",
"Fire Xweetok Morphing Potion",
"Fire Yurble Morphing Potion",
"Fish Bone Bruce Sword",
"Fish Doughnutfruit",
"Fish Negg Plushie",
"Fishy Delight Grarrl Gobstopper",
"Flame Reflectozap",
"Flaming Torch",
"Flankin",
"Fleaf",
"Floppy Turtum Plushie",
"Floral Jelly",
"Floral Maractite Coin",
"Flosset",
"Flotsam Amulet of the Champion",
"Flotsam Chestplate of the Champion",
"Flotsam Shell Shield",
"Flotsam Shell Sword",
"Floud Balloon",
"Floud Bomb",
"Flying Fireball",
"Foil Food Shop Stamp",
"Foil Slorg Stamp",
"Forbidden Zafara",
"Force Shield",
"Fountain of Youth",
"Four Layer Carrot Cake",
"French Onion Soup",
"Fresh Fruit Goblet",
"Fresh Lobster Tail",
"Freshly Cut Grass Slushie",
"Fright Pop",
"Frost Lizard Plushie",
"Frozen Lizard Plushie",
"Frozen Scroll",
"Full Acara Armour",
"Full Aisha Armour",
"Full Blumaroo Armour",
"Full Bori Armour",
"Full Bruce Armour",
"Full Buzz Armour",
"Full Chia Armour",
"Full Chomby Armour",
"Full Cybunny Armour",
"Full Draik Armour",
"Full Elephante Armour",
"Full Eyrie Armour",
"Full Flotsam Armour",
"Full Gelert Armour",
"Full Gnorbu Armour",
"Full Grarrl Armour",
"Full Grundo Armour",
"Full Hissi Armour",
"Full Ixi Armour",
"Full Jetsam Armour",
"Full JubJub Armour",
"Full Kau Armour",
"Full Kiko Armour",
"Full Korbat Armour",
"Full Kougra Armour",
"Full Krawk Armour",
"Full Kyrii Armour",
"Full Lenny Armour",
"Full Lupe Armour",
"Full Lutari Armour",
"Full Meerca Armour",
"Full Moehog Armour",
"Full Mynci Armour",
"Full Nimmo Armour",
"Full Ogrin Armour",
"Full Peophin Armour",
"Full Poogle Armour",
"Full Pteri Armour",
"Full Quiggle Armour",
"Full Ruki Armour",
"Full Scorchio Armour",
"Full Shoyru Armour",
"Full Skeith Armour",
"Full Techo Armour",
"Full Tonu Armour",
"Full Tuskaninny Armour",
"Full Uni Armour",
"Full Usul Armour",
"Full Xweetok Armour",
"Full Yurble Armour",
"Full Zafara Armour",
"Fun in the Sun Usuki Reject",
"Furry Autumn Bushes",
"Furry Lupe Staff",
"Fyora Apple",
"Geb",
"Gelert Blade of Frozen Wrath",
"Gelert Frostweaver Shield",
"Gelert Spiked Shield",
"Gelert Throwing Bone",
"Gelupepper",
"Geopeppers",
"Ghost Acara Morphing Potion",
"Ghost Draik Morphing Potion",
"Ghost Elephante Morphing Potion",
"Ghost Evil Fuzzle",
"Ghost Fuzzle",
"Ghost Gelert Morphing Potion",
"Ghost Grarrl Morphing Potion",
"Ghost Hissi Morphing Potion",
"Ghost Kiko Morphing Potion",
"Ghost Korbat Morphing Potion",
"Ghost Lenny Morphing Potion",
"Ghost Peophin Morphing Potion",
"Ghost Shoyru Morphing Potion",
"Ghost Techo Morphing Potion",
"Ghost Tuskaninny Morphing Potion",
"Ghostkerchief",
"Gifts for your Enemies",
"Gilded Kougra Chestplate",
"Gilded Ruki Flail",
"Gilly the Usul",
"Glack",
"Glaring Pumpkin",
"Gloom Kougra Plushie",
"Glowing Bath Tub",
"Glowing Bed",
"Glowing Cauldron",
"Glowing Korbat Morphing Potion",
"Glowing Maractite Wand",
"Glowing Mirror",
"Glowing Rug",
"Glowing Sofa",
"Glowing Table",
"Glowing Tuskaninny Wand",
"Glyme",
"Glyme Perfume",
"Gnome Shroom",
"Gold Balloon",
"Gold Tonu Morphing Potion",
"Gold Velvet Chair",
"Golden Bori Bow",
"Golden Bori Staff",
"Golden Candy Cane Sword",
"Golden Caviar",
"Golden Coltzan Statue",
"Golden Doughnutfruit",
"Golden Full Kacheek Armour",
"Golden Garden Bench",
"Golden Juppie",
"Golden Korbat Charm",
"Golden Kougra Slingshot",
"Golden Lupe Bone Sword",
"Golden Moehog Tusk Guards",
"Golden Peophin Harp",
"Golden Qasalan Chestpiece",
"Golden Ruki Brooch",
"Golden Scamander Scroll",
"Golden Scarab Shield",
"Gondolier Usuki",
"Gooseberry Crepe",
"Gorerito",
"Graduate Usuki",
"Grape Jelly Sword",
"Grapefruit Cake",
"Grarrl Claw",
"Greater Defence Scroll",
"Greater Elemental Potion",
"Greater Fire Potion",
"Greater Healing Scroll",
"Green Acara Morphing Potion",
"Green Attack Stilts",
"Green Blumaroo Morphing Potion",
"Green Bori Morphing Potion",
"Green Buzz Morphing Potion",
"Green Chia Morphing Potion",
"Green Clockwork Hissi",
"Green Doughnutfruit",
"Green Draik Morphing Potion",
"Green Flotsam Morphing Potion",
"Green Gelert Morphing Potion",
"Green Grarrl Morphing Potion",
"Green Jetsam Morphing Potion",
"Green JubJub Morphing Potion",
"Green Kacheek Morphing Potion",
"Green Kau Morphing Potion",
"Green Koi Morphing Potion",
"Green Korbat Morphing Potion",
"Green Kougra Morphing Potion",
"Green Krawk Morphing Potion",
"Green Lenny Morphing Potion",
"Green Lupe Morphing Potion",
"Green Meerca Morphing Potion",
"Green Moehog Morphing Potion",
"Green Mynci Morphing Potion",
"Green Nimmo Morphing Potion",
"Green Peophin Morphing Potion",
"Green Picnic Hamper",
"Green Poogle Morphing Potion",
"Green Pteri Morphing Potion",
"Green Quiggle Morphing Potion",
"Green Shoyru Tail Armour",
"Green Shoyru Wing Armour",
"Green Skeith Morphing Potion",
"Green Techo Bow",
"Green Techo Morphing Potion",
"Green Tonu Morphing Potion",
"Green Tuskaninny Morphing Potion",
"Green Usul Morphing Potion",
"Green Wocky Morphing Potion",
"Green Zafara Morphing Potion",
"Greevix",
"Grey Faerie Axe",
"Grey Faerie Mushroom",
"Grey Grarrl Morphing Potion",
"Grey Ixi Morphing Potion",
"Grey JubJub Morphing Potion",
"Grey Korbat Morphing Potion",
"Grey Lenny Morphing Potion",
"Grey Mynci Morphing Potion",
"Grey Mynci Plushie",
"Grey Sword",
"Grey Techo Morphing Potion",
"Grey Yurble Morphing Potion",
"Grey Zafara Morphing Potion",
"Grumblebug",
"Grundo Backpack",
"Grundo Independence Day Usuki",
"Grundo Tales",
"Guardian of Fire Magic Plushie",
"Guide to Dilapidated Homes",
"Guide to the Neocola Machine",
"Gwortz",
"Halloween Aisha Morphing Potion",
"Halloween Blumaroo Morphing Potion",
"Halloween Candy Cane",
"Halloween Chia Morphing Potion",
"Halloween Cybunny Morphing Potion",
"Halloween Draik Plushie",
"Halloween Grarrl Morphing Potion",
"Halloween Grundo Notebook",
"Halloween Hissi Morphing Potion",
"Halloween Ixi Morphing Potion",
"Halloween JubJub Plushie",
"Halloween Kau Morphing Potion",
"Halloween Korbat Morphing Potion",
"Halloween Kyrii Morphing Potion",
"Halloween Lenny Morphing Potion",
"Halloween Meerca Morphing Potion",
"Halloween Nimmo Morphing Potion",
"Halloween Techo Morphing Potion",
"Halloween Uni Morphing Potion",
"Hamarama Ice Lolly",
"Hand Carved Blumaroo Bow",
"Hand Carved Draik Slingshot",
"Hand Carved Shoyru Wand",
"Hand Stitched Usul Dagger",
"Hand Stitched Usul Hammer",
"Hannah Plushie",
"Hannah Quiguki",
"Happy Birthday Pizza",
"Hardened Ruki Claws",
"Hasee",
"Hasee T-Shirt",
"Hawaiian Usuki Reject",
"Healing Ankh of the Nimmo",
"Heart Shaped Bed",
"Heavy Blue Tunic",
"Heavy Wooden Kau Shield",
"Highland Chia Battle Shield",
"Highland Chia War Hammer",
"Highland Chia War Paint",
"Hilarious Pumpkin",
"Hissing Techo Staff",
"Holographic Coltzans Shrine Stamp",
"Holographic Magax Stamp",
"Holographic Virtupets Stamp",
"Honey Blossom",
"Honey Goo Blaster",
"Honeycomb Buzz Shield",
"Horned Grarrl Slingshot",
"How to Get Past the Guard",
"Hydro Hammer",
"I got taxed by the Tax Beast T-Shirt",
"I Love Buzzer T-Shirt",
"I Love Chezzoom T-Shirt",
"I Love Faerie Cadro T-Shirt",
"I Love Hornsby T-Shirt",
"I Love Kadoatie T-Shirt",
"I Love Khamette T-Shirt",
"I Love Lord Kass Bean Bag",
"I Love Lord Kass Bed",
"I Love Lyins T-Shirt",
"I Love Scarabug T-Shirt",
"I Love Selket T-Shirt",
"I Love Splyke T-Shirt",
"I Love Spyder T-Shirt",
"I Love Tenna T-Shirt",
"I Love Wadjet T-Shirt",
"Ice Hissi Morphing Potion",
"Ice Sceptre",
"Ice Shield",
"Icy Blade of Terror Mountain",
"Icy Bruce Boomerang Of Doom",
"Icy Chia Goggles",
"Icy Doughnutfruit",
"Icy Glove",
"Igneot Stamp",
"Ilere Crayons",
"Illusens Diary",
"Illusens Gems",
"Illusens Hip Blade",
"Illusens Really Sharp Stick",
"Illusens Silver Shield",
"Inferno Lizard Plushie",
"Inside the Mind of Bob",
"Inverted Space Faerie Stamp",
"Invisible Wocky Morphing Potion",
"Iron Lupe Collar",
"Island Blumaroo Morphing Potion",
"Island Bori Morphing Potion",
"Island Bruce Morphing Potion",
"Island Buzz Morphing Potion",
"Island Cybunny Morphing Potion",
"Island Eyrie Morphing Potion",
"Island Gelert Morphing Potion",
"Island Grundo Morphing Potion",
"Island Ixi Morphing Potion",
"Island JubJub Morphing Potion",
"Island Kiko Morphing Potion",
"Island Koi Morphing Potion",
"Island Korbat Morphing Potion",
"Island Krawk Morphing Potion",
"Island Lenny Morphing Potion",
"Island Lupe Morphing Potion",
"Island Mynci Morphing Potion",
"Island Nimmo Morphing Potion",
"Island Ogrin Morphing Potion",
"Island Peophin Morphing Potion",
"Island Poogle Morphing Potion",
"Island Quiggle Morphing Potion",
"Island Shoyru Morphing Potion",
"Island Skeith Morphing Potion",
"Island Techo Morphing Potion",
"Island Tuskaninny Morphing Potion",
"Island Uni Morphing Potion",
"Island Wocky Morphing Potion",
"Island Zafara Morphing Potion",
"It Came From Kreludor",
"Itchi",
"Ixi Elixir of the Woods",
"Ixi Hoof Blade",
"Jagged Krawk Blade",
"Jahbal Plushie",
"Jam Filled Battle Biscuit",
"Jar of Spiders",
"Jelly Finger",
"Jelly Garden Fountain",
"Jelly Negg",
"Jelly Spider Eyeball",
"Jellybean Tree",
"Jeran Gnome",
"Jeran Quiguki",
"Jeran Usuki",
"Jermite",
"Jhudora Statue",
"Jiggybug",
"Jolly Pumpkin",
"JubJub Flame Ball",
"JubJub Foot Hardening Lotion",
"JubJub Padded Paws",
"JubJub Tickler",
"Kacheek Extinguisher",
"Kacheek Flour",
"Kacheek Pebble Lobber",
"Kadoatie",
"Kadoatie Usuki Set",
"Kass Toy Box",
"Kau Pastures",
"Kauvara",
"Kauvaras Potion",
"Kaylas Golden Brew",
"Kaylas Hat",
"Kaylas Magic Cloak",
"Keeper Of Time Plushie",
"Khan the Unstoppable",
"Khonsu",
"Kiko Helm of Intellect",
"Kiko Throwing Plasters",
"Kikovision Goggles",
"King Altador Stamp",
"King Hagan Quiguki",
"King Jazan Stamp",
"King Kelpbeard Stamp",
"King Skarl Plushie",
"King Skarl Quiguki",
"King Skarl Usuki",
"King Terask Plushie",
"Koi Amulet",
"Koi Full Armour",
"Korbat Power Blaster",
"Korbat Wing Blade",
"Kougra Classics",
"Kougra Power Sword",
"Kougra Wing Collar",
"Kougra Wool Bomb",
"Krakuberries",
"Krawk",
"Krawk T-Shirt",
"Kreludor Mining Corridor Maps",
"Kyrii Sorceror",
"Kyrii Spoonapult",
"Kyrii Swordhammer",
"Lab Ray Stamp",
"Lady Blurg",
"Large Black Collectable Scarab",
"Larnikin",
"Last Avocado Bomb",
"Lava Arrow",
"Lavaberry",
"Lawyerbot Self-Portrait",
"Lazulite Dervish Plushie",
"Leaded Elemental Vial",
"Leaded Light Vial",
"Leaded Water Vial",
"Leather Xweetok Helmet",
"Leirobas Plushie",
"Lenny Cookbook",
"Lenny Witchcraft",
"Lesser Defence Scroll",
"Light Faerie Backpack",
"Light Faerie Doll",
"Light Faerie Dust",
"Light Faerie Sofa",
"Light Faerie Token",
"Lightmite",
"Lightning Giant Plushie",
"Lightning Lizard Plushie",
"Lightning Scroll",
"Lightweight Bori Sword",
"Lightweight Buzz Axe",
"Lightweight Xweetok Spear",
"Linked Hot Dogs",
"Little Brother Usuki",
"Locating Iron",
"Long Glowing Drawer",
"Lord Darigan",
"Lord Kass Card",
"Lord Kass Gnome",
"Lord Kass Plushie",
"Lord Kass Stamp",
"Lord Kass Usuki",
"Lost Desert Quiguki",
"Lost Desert Usuki",
"Lucky Uni Charm",
"Lupe Chia Bomb",
"Lupe Grabber Jaw",
"Luxury Cabbage Cake",
"Luxury Castle Petpet Bed",
"Luxury Faerie Festival Snowglobe",
"Magical Agueena Chia Pop",
"Magical Apple Chia Pop",
"Magical Asparagus Chia Pop",
"Magical Aubergine Chia Pop",
"Magical Avocado Chia Pop",
"Magical Banana Chia Pop",
"Magical Blue Flotsam Plushie",
"Magical Blue Kacheek Plushie",
"Magical Blue Kiko Plushie",
"Magical Blue Krawk Plushie",
"Magical Blue Nimmo Plushie",
"Magical Blue Shoyru Plushie",
"Magical Blue Tonu Plushie",
"Magical Blue Yurble Plushie",
"Magical Blueberry Chia Pop",
"Magical Carrot Chia Pop",
"Magical Chokato Chia Pop",
"Magical Cloud Gelert Plushie",
"Magical Cloud Lenny Plushie",
"Magical Coconut Chia Pop",
"Magical Durian Chia Pop",
"Magical Ghost Marshmallows Plushie",
"Magical Gooseberry Chia Pop",
"Magical Grape Chia Pop",
"Magical Green Elephante Toy",
"Magical Green Flotsam Plushie",
"Magical Green Gelert Plushie",
"Magical Green Kiko Plushie",
"Magical Green Koi Plushie",
"Magical Green Krawk Plushie",
"Magical Green Tonu Plushie",
"Magical Green Wocky Plushie",
"Magical Green Yurble Plushie",
"Magical Hair Usuki Reject",
"Magical Juppie Swirl Chia Pop",
"Magical Lemon Chia Pop",
"Magical Lime Chia Pop",
"Magical MSP Poogle Plushie",
"Magical Onion Chia Pop",
"Magical Orange Chia Pop",
"Magical Pea Chia Pop",
"Magical Peach Chia Pop",
"Magical Pear Chia Pop",
"Magical Pepper Chia Pop",
"Magical Pineapple Chia Pop",
"Magical Pirate Krawk Plushie",
"Magical Plum Chia Pop",
"Magical Potato Chia Pop",
"Magical Purple Blumaroo Plushie",
"Magical Purple Koi Plushie",
"Magical Purple Zafara Plushie",
"Magical Rainbow Aisha Plushie",
"Magical Rainbow Blumaroo Plushie",
"Magical Rainbow Cybunny Plushie",
"Magical Red Blumaroo Plushie",
"Magical Red Gelert Plushie",
"Magical Red Grarrl Plushie",
"Magical Red Kiko Plushie",
"Magical Red Koi Plushie",
"Magical Red Krawk Plushie",
"Magical Red Lenny Plushie",
"Magical Red Nimmo Plushie",
"Magical Red Skeith Plushie",
"Magical Red Starry Slushie",
"Magical Red Tonu Plushie",
"Magical Red Usul Plushie",
"Magical Red Wocky Plushie",
"Magical Red Yurble Plushie",
"Magical Spotted Blumaroo Plushie",
"Magical Sroom Chia Pop",
"Magical Starry Kau Plushie",
"Magical Strawberry Chia Pop",
"Magical Thornberry Chia Pop",
"Magical Tomato Chia Pop",
"Magical Ummagine Chia Pop",
"Magical Yellow Kiko Plushie",
"Magical Yellow Lenny Plushie",
"Magical Yellow Nimmo Plushie",
"Magical Yellow Skeith Plushie",
"Magical Yellow Tonu Plushie",
"Magical Yellow Wocky Plushie",
"Magical Yellow Yurble Plushie",
"Malediction for Beginners",
"Mango Jelly Club",
"Maractite Acara Shield",
"Maractite Aisha Morphing Potion",
"Maractite Dimensional Trap",
"Maractite Draik Morphing Potion",
"Maractite Hissi Morphing Potion",
"Maractite Ice Lolly",
"Maractite Krawk Morphing Potion",
"Maractite Mace",
"Maractite Peophin Morphing Potion",
"Maractite Scimitar",
"Maractite Shell Shield",
"Marafalop",
"Maraquan Acara Morphing Potion",
"Maraquan Aisha Bow",
"Maraquan Draik Cloak",
"Maraquan Draik Dagger",
"Maraquan Gelert Morphing Potion",
"Maraquan Grarrl Morphing Potion",
"Maraquan Kacheek Morphing Potion",
"Maraquan Korbat Morphing Potion",
"Maraquan Krawk Morphing Potion",
"Maraquan Meerca Morphing Potion",
"Maraquan Mynci Morphing Potion",
"Maraquan Techo Morphing Potion",
"Maraquan Usul Morphing Potion",
"Marillis Harbane",
"Master Wizards Cape",
"Mayor Thumburt Usuki",
"Mecha Hot Dog",
"Meepit Muffins",
"Meerca Gloves of Agility",
"Meerca Pie",
"Meerca Speed Potion",
"Meerca Tail Shield",
"Mega Fire Shield",
"Mega Honeyplume Smoothie",
"Mega Lemon Blitz Smoothie",
"Mega Salmon Sherbert Smoothie",
"Mega Sandwich",
"Mega U-Bend",
"Melatite Dervish Plushie",
"Meridell Toy Box",
"Meridell Usuki",
"Meridell Usuki King",
"Meridell Usuki Queen",
"Meridellian Style Mashed Potatoes",
"Mighty Steakwich",
"Mighty Techo Chest Plate",
"Mighty Techo Hammer",
"Mime Quiguki",
"Mini Baby Hot Dogs",
"Mini Giant Jelly",
"Mini Throwing Toasts",
"Minor Defence Scroll",
"Minty Eyrie Cookie",
"Misaligned Printer Stamp",
"Misprint Meuka Stamp",
"Mist Kougra Plushie",
"Mistletoe Potion",
"Moach",
"Moach Eraser",
"Modern Lupe Magazine",
"Modern Spells",
"Moehog Bristle Dagger",
"Moehog Crossbow",
"Moehog Matching",
"Moehog Slingshot",
"Moffit",
"Mokti Plushie",
"Moltenore",
"Money Tree Coin",
"Monoceraptor Plushie",
"Monoceraptors Toenail",
"Mootix",
"Mootix Table",
"Moquot",
"Mortog",
"Mouldy Cheese",
"Mozito",
"MSPP Backpack",
"MSPP Plushie",
"Murky Green",
"Must-Have Figure Assortment",
"Mutant Chia Plushie",
"Mutant Golf Club",
"Mutant Korbat Plushie",
"Mutant Kougra Plushie",
"Mutant Krawk Plushie",
"Mutant Loveseat",
"Mutant Shoyru Plushie",
"Mystical Ixi Hooded Cape",
"Mystical Nimmo Amulet",
"Need a Better Printer Stamp",
"Negg Faerie Doll",
"Negg Faerie Usuki Set",
"Neopian Heroes",
"Neoquest Gatekeeper Plushie",
"NeoQuest Hero Plushie",
"Neotruffle",
"Neutralising Ray",
"Nibbled Cooking Pot Stamp",
"Nimmo Battle Cry",
"Nimmo Elixir of Healing",
"Nimmo Throwing Star",
"Nocan Vish",
"Nova Blade",
"Oaken Kacheek Sword",
"Official Usuki Battle Set",
"Old Beaten Chokato Chia Plushie",
"Olde Zafara",
"Olivetato",
"One Hundred Million Neopoint Stamp",
"Onion and Mustard Pie",
"Oozing Tulip",
"Orange Jelly Guitar",
"Orange Yurble Morphing Potion",
"Ornate Buzz Chestplate",
"Ornate Buzz Stinger",
"Ornate Ivory Love Spoon",
"Ornate Jetsam Battle Helmet",
"Ornate Jetsam Bow",
"Ornate Jetsam Hammer",
"Ornate Jetsam Shield",
"Ornate Usuki",
"Ornate Violet Cloak",
"P-Bomb",
"Padded Bruce Jacket",
"Padded Cybunny Claw",
"Padded Cybunny Gloves",
"Padded Mynci Gloves",
"PaintBrush Coin",
"Painted Techo Club",
"Palace Guard Bracers",
"Palace Guard Helmet",
"Palace Guard Sandals",
"Palace Guard Sword",
"Palace Guard Tunic",
"Pan Galactic Gargle Slushie",
"Parts on a Pizza",
"Pastel Cybunny Morphing Potion",
"Peachy Pizza",
"Peanut and Chocolate Slushie",
"Pearl Koi Slingshot",
"Pencil of Nova",
"Pencil of the Space Faerie",
"Peophin Bubble",
"Peophin Emblazoned Maractite Shield",
"Peophin Magical Medallion",
"Petfolio",
"Phear",
"Pickled Cauliflower",
"Pinanna Plus",
"Pinceron T-Shirt",
"Pinchit",
"Pink Apple Lantern",
"Pink Blooky T-Shirt",
"Pink Chokato",
"Pink Clockwork Poogle",
"Pink Flosset T-Shirt",
"Pink Kadoatie T-Shirt",
"Pink Lenny Morphing Potion",
"Pink Ruki Morphing Potion",
"Pink Walein T-Shirt",
"Pirate Bori Morphing Potion",
"Pirate Captain Usuki",
"Pirate Cybunny Morphing Potion",
"Pirate Eyrie Morphing Potion",
"Pirate Flotsam Morphing Potion",
"Pirate Gnorbu Morphing Potion",
"Pirate Kacheek Morphing Potion",
"Pirate Kougra Morphing Potion",
"Pirate Krawk Plushie",
"Pirate Lenny Morphing Potion",
"Pirate Poogle Morphing Potion",
"Pirate Slingshot",
"Pirate Spear",
"Pirate Techo Morphing Potion",
"Pirate Usul Morphing Potion",
"Pirate Wocky Morphing Potion",
"Pirates Chest",
"PIZZA OF DEATH",
"Plum",
"Plush Gelert Collar",
"Plushie Aisha Morphing Potion",
"Plushie Bori Morphing Potion",
"Plushie Bruce Morphing Potion",
"Plushie Buzz Morphing Potion",
"Plushie Chomby Morphing Potion",
"Plushie Cybunny Morphing Potion",
"Plushie Flotsam Morphing Potion",
"Plushie Gnorbu Morphing Potion",
"Plushie Grarrl Morphing Potion",
"Plushie Grundo Morphing Potion",
"Plushie Hissi Morphing Potion",
"Plushie Jetsam Morphing Potion",
"Plushie Kau Morphing Potion",
"Plushie Kiko Morphing Potion",
"Plushie Korbat Morphing Potion",
"Plushie Ogrin Morphing Potion",
"Plushie Poogle Morphing Potion",
"Plushie Scorchio Morphing Potion",
"Plushie Skeith Morphing Potion",
"Plushie Techo Morphing Potion",
"Plushie Tuskaninny Morphing Potion",
"Plushie Usul Morphing Potion",
"Plushie Yurble Morphing Potion",
"Pocket Satellite",
"Pofew",
"Poison Muffin",
"Polka Carrot",
"Polkadot Tonu Morphing Potion",
"Pomanna Plushie",
"Poogle Fang Amulet",
"Poogle Lightning Boots",
"Poogle Liquid Freeze Potion",
"Poogle Pages",
"Poogle Slingshot",
"Pootato",
"Pop Star Quiguki",
"Pot of Darkness",
"Potato Potion",
"Potion of Night",
"Potion of Skeith Scales",
"Prickly Merato",
"Princess Vyssas Diary",
"Professional Curses",
"Professor Kachevski",
"Prom Date Usuki Reject",
"Psellias Blessing",
"Pteri Battle Whistle",
"Pteri Dagger",
"Pteri Egg Shot",
"Pteri Precision Helmet",
"Pteri Throwing Feathers",
"Pumpkin Club",
"Pumpkin Scoopings",
"Punchbag Bob",
"Punk Rocker Hot Dog",
"Purple Doughnutfruit",
"Purple Draik Morphing Potion",
"Purple Eyrie Morphing Potion",
"Purple Grundo Morphing Potion",
"Purple Peophin Morphing Potion",
"Purple Pteri Morphing Potion",
"Purple Shoyru Morphing Potion",
"Purple Techo Morphing Potion",
"Purple Tonu Morphing Potion",
"Puzzle Fruit",
"Pyramid Purpple",
"Pyramid Strawberry",
"Qasalan Throwing Axe",
"Queen Fyora Stamp",
"Quiggle Leaping Boots",
"Quiggle Pie",
"Quiggle Statue",
"Quiggle Sword of Terror",
"Quiguki Mermaid",
"Quiguki Musketeer",
"Quiguki Prom Queen",
"Quiguki Zombie",
"Quilin",
"Rainblug",
"Rainbow Bath Tub",
"Rainbow Candy Floss",
"Rainbow Carrot",
"Rainbow Chomby Morphing Potion",
"Rainbow Cybunny Negg",
"Rainbow Doughnutfruit",
"Rainbow Evil Fuzzle",
"Rainbow Flotsam Morphing Potion",
"Rainbow Frost Cannon",
"Rainbow Grundo Plushie",
"Rainbow Hissi Morphing Potion",
"Rainbow JubJub Morphing Potion",
"Rainbow Kau Morphing Potion",
"Rainbow Koi Morphing Potion",
"Rainbow Kyrii Morphing Potion",
"Rainbow Lupe Morphing Potion",
"Rainbow Pencil",
"Rainbow Scooter",
"Rainbow Scorchstone",
"Rainbow Sticky Hand",
"Rainbow Swirly Potion",
"Rainbow Tuskaninny Plushie",
"Rainbow Uni Plushie",
"Rainbow Wocky Morphing Potion",
"Raptraphant Leg",
"Razul Plushie",
"Red Acara Morphing Potion",
"Red Blumaroo Morphing Potion",
"Red Bori Morphing Potion",
"Red Brick Bath Tub",
"Red Bruce Morphing Potion",
"Red Buzz Morphing Potion",
"Red Chia Morphing Potion",
"Red Clockwork Grundo",
"Red Cybunny Morphing Potion",
"Red Draik Morphing Potion",
"Red Elephante Morphing Potion",
"Red Eyrie Morphing Potion",
"Red Flotsam Morphing Potion",
"Red Gelert Morphing Potion",
"Red Grarrl Morphing Potion",
"Red Ixi Morphing Potion",
"Red Jetsam Morphing Potion",
"Red Kacheek Morphing Potion",
"Red Kau Morphing Potion",
"Red Kiko Morphing Potion",
"Red Koi Morphing Potion",
"Red Korbat Morphing Potion",
"Red Kougra Morphing Potion",
"Red Kyrii Morphing Potion",
"Red Lenny Morphing Potion",
"Red Moehog Morphing Potion",
"Red Moltite Popsicle",
"Red Mynci Morphing Potion",
"Red Nimmo Morphing Potion",
"Red Peophin Morphing Potion",
"Red Pteri Morphing Potion",
"Red Shoyru Morphing Potion",
"Red Skateboard",
"Red Skeith Morphing Potion",
"Red Techo Morphing Potion",
"Red Usul Morphing Potion",
"Red Wocky Balloon",
"Red Wocky Morphing Potion",
"Red Yurble Boots",
"Red Yurble Breast Plate",
"Red Yurble Ear Guards",
"Red Yurble Gauntlets",
"Red Yurble Morphing Potion",
"Red Zafara Morphing Potion",
"Regal Draik Wand",
"Regulation Chainmail",
"Reinforced Maractite Shield",
"Reject Blue Acara Plushie",
"Reject Gelert Plushie",
"Reject Green Acara Plushie",
"Reject Red Acara Plushie",
"Reject Yellow Acara Plushie",
"Relic Chia Morphing Potion",
"Rikti Plushie",
"Rings of Fire",
"Roast Pork",
"Robo Blumaroo",
"Roe Sushi",
"Rollatron",
"Rotoblur 4000",
"Royal Boy Kyrii Morphing Potion",
"Royal Girl Kyrii Morphing Potion",
"Royal Play Pen",
"Ruby Encrusted Sceptre",
"Ruby Krawk Shield",
"Ruby Krawk Stun Ray",
"Runny Snot",
"Rustic Aisha Blade",
"Sack of Garlic Powder",
"Sack Of Kougranip",
"Sakhmetian Axe",
"Sakhmetian Dagger",
"Sakhmetian Shield",
"Sakhmetian Spear",
"Sargug",
"Sasha Stamp",
"Scamander",
"Scarab Medallion",
"Scarescorchio",
"Scary Spider",
"Scoach",
"Scorchio Battle Wand",
"Scorchio Calculator",
"Scorchio Molten Battle Shield",
"Scorchio Molten Tail Guard",
"Scowling Sloth Coin",
"Scriblet",
"Scroll of Dark Nova",
"Scroll of Flame Strike",
"Scroll of Freezing",
"Scroll of the Western Winds",
"Scroll Potion",
"Scuzzy Stamp",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secret Laboratory Map",
"Secrets of Tombola",
"Sergeant Brexis",
"Serpentine Dervish Plushie",
"Shadow Armour",
"Shadow Axe",
"Shadow Blumaroo Morphing Potion",
"Shadow Chomby Morphing Potion",
"Shadow Cybunny Morphing Potion",
"Shadow Kougra Plushie",
"Shadow Lantern",
"Shadow Lenny Morphing Potion",
"Shadow Ogrin Morphing Potion",
"Shadow Peophin Morphing Potion",
"Shadow Ruki Morphing Potion",
"Shadow Skeith Morphing Potion",
"Shadow Usul Plushie",
"Shadow Usul Stories",
"Sharp Fire Disc",
"Sharpened Hook",
"Shenkuu Stamp",
"Shimmering Acara Breastplate",
"Shock Lizard Plushie",
"Short Sleeved Yellow Tunic",
"Shoyru Battle Shield",
"Shoyru Pink Aviator Jacket",
"Shoyru Statue",
"Shoyru Sword",
"Shuriken",
"Sidney Plushie",
"Silver Doughnutfruit",
"Silver Draik Bow",
"Silver Draik Chestplate",
"Silver Draik Wing Guards",
"Silver Kacheek Armour",
"Silver Korbat Amulet",
"Silverware Set",
"Siona",
"Skeith Destructo Horn",
"Skeith Inferno Spell",
"Skidget",
"Skootle Bug",
"Skritch",
"Skuffler",
"Skull Full of Sand",
"Skunk Buzz Morphing Potion",
"Skunk Eyrie Morphing Potion",
"Skunk Flotsam Morphing Potion",
"Skunk Mynci Plushie",
"Sledge Shield",
"Slimy Tree",
"Slorg Slime",
"Sloth Wrap",
"Smiling Space Faerie Coin",
"Snailien",
"Sniddberry Meerca Gobstopper",
"Snorkle Pudding",
"Snot Blocks",
"Snot Helmet",
"Snot Slingshot",
"Snot Spear",
"Snotbunny",
"Snotty Hammer",
"Snotty Sword",
"Snow Aisha Morphing Potion",
"Snow Blumaroo Morphing Potion",
"Snow Bori Morphing Potion",
"Snow Bruce Morphing Potion",
"Snow Chia Morphing Potion",
"Snow Eyrie Morphing Potion",
"Snow Flame",
"Snow Ogrin Morphing Potion",
"Snow Peophin Morphing Potion",
"Snow Techo Morphing Potion",
"Snow Usul Morphing Potion",
"Snow Wocky Morphing Potion",
"Snowbunny Stamp",
"Snowflake Pendant",
"Snowickle",
"Songray",
"Sonic Melter",
"Sophie, A Biography",
"Soup Faerie Doll",
"Souper Bowl",
"Space Faerie Doll",
"Space Faerie Lunch Box",
"Space Faerie Mushroom",
"Space Prom Date Usuki Reject",
"Space Scrap Shield",
"Sparkling Acara Shield",
"Speckled Bruce Plushie",
"Speckled Cybunny Morphing Potion",
"Speckled Nimmo Plushie",
"Spiked Eyrie Band",
"Spirkle",
"Split Bruce Morphing Potion",
"Split Chia Morphing Potion",
"Split Flotsam Morphing Potion",
"Sponge Doughnutfruit",
"Spooky Ghostbeef",
"Spoooky Muffin",
"Spotted Flotsam Morphing Potion",
"Spotted Gelert Morphing Potion",
"Spotted Gelert Plushie",
"Spotted Jetsam Morphing Potion",
"Spotted Kau Morphing Potion",
"Spotted Kau Shield",
"Spotted Kau Sword",
"Spotted Koi Morphing Potion",
"Spotted Koi Plushie",
"Spotted Kougra Morphing Potion",
"Spotted Nimmo Morphing Potion",
"Spotted Pteri Morphing Potion",
"Springabee",
"Squippit",
"Squishy Shoyru Healing Stone",
"Stack It High Cake",
"Staff of Garlicness",
"Staff of Supernova",
"Staff of Ultranova",
"Stained Glass Sophie Window",
"Star Tree",
"Starry Bruce Morphing Potion",
"Starry Cybunny Morphing Potion",
"Starry Draik Morphing Potion",
"Starry Draik Plushie",
"Starry Eyrie Morphing Potion",
"Starry Grundo Morphing Potion",
"Starry Kacheek Morphing Potion",
"Starry Kau Morphing Potion",
"Starry Nimmo Morphing Potion",
"Starry Scorchio Morphing Potion",
"Starry Skeith Morphing Potion",
"Starry Yurble Morphing Potion",
"Starry Zafara Morphing Potion",
"Stealthy Blumaroo Morphing Potion",
"Stealthy Grarrl Morphing Potion",
"Stealthy Krawk Morphing Potion",
"Stealthy Kyrii Morphing Potion",
"Stealthy Lutari Morphing Potion",
"Stealthy Nimmo Boots",
"Stealthy Pencil Case",
"Stealthy Techo Morphing Potion",
"Steel Chomby Sword",
"Steel Golem Neoquest Plushie",
"Sticky Quiggle Flicky Thing",
"Sticky Snowflake Stamp",
"Stone Bedside Table",
"Stone Snowflake",
"Storm Amulet",
"Strale",
"Strange Bulb",
"Strange Metal Usuki",
"Strange Pinanna",
"Strange Potion",
"Strawberry Techo Morphing Potion",
"Strawberry Tuskaninny Morphing Potion",
"Striped Chia Morphing Potion",
"Striped Flotsam Morphing Potion",
"Striped Grarrl Morphing Potion",
"Striped Jetsam Morphing Potion",
"Striped Kau Morphing Potion",
"Striped Nimmo Morphing Potion",
"Striped Shoyru Morphing Potion",
"Striped Skeith Morphing Potion",
"Striped Tuskaninny Morphing Potion",
"Striped Xweetok Morphing Potion",
"Strong Berry",
"Studded Bruce Bow Of Protection",
"Summer Fun Usuki",
"Super Attack Bacon",
"Super Hero Usuki",
"Super Sand Grain",
"Super Secret Guide to the Defenders of Neopia Headquarters",
"Superior Reflection Shield",
"Sushi Boat",
"Swamp Ghoul",
"Swamp Lupe Neoquest Plushie",
"Swirling Seaweed Orb",
"Sword of Trumpeting",
"Taelia Quiguki",
"Taelias Snowball",
"Tall Pumpkin",
"Tangle Net Gun",
"Tar Slushie",
"Tartan Chia Pop",
"Tax Beast Plushie",
"Techo Dagger Of Speed",
"Techo Master Lunchbox",
"Techo Statue",
"Teenage Usuki Reject",
"Terask Stamp",
"The Bad Skeith",
"The Eve of the Eve",
"The Great Battle Stamp",
"The Hikalakas Totem",
"The Incredible Grarrl",
"The Legendary Sutek Scroll",
"The Magic Staff",
"The Pyramid Tablets",
"The Scroll of Scrolls",
"The Shadow Usul",
"The Tax Beast",
"The Three Poster",
"The Three Stamp",
"The Voodoo Techo",
"Thornberry",
"Thunder Lizard Plushie",
"Thyoras Tear",
"Ticking Eyrie Bomb",
"Tiger Orange Slushie",
"Tiger Sofa",
"Tigersquash",
"Tigersquash Spectacular",
"Toast Shield",
"Tofu Space Slug Soup",
"Tomato Kebab",
"Tonu Golden Horn",
"Tooth Faerie Doll",
"Toothbrush Sword",
"Tootum",
"Tower Shield",
"Traditional Welsh Quiguki",
"Transparaberry Slushie",
"Transparent Elephante Morphing Potion",
"Transparent Korbat Morphing Potion",
"Transparent Lenny Morphing Potion",
"Transparent Skeith Morphing Potion",
"Tribal Desert Garb",
"Trigonometry Hyperbolics",
"Triple Choco-Strawberry Cake",
"Triple Turbo Dryer",
"Turmac",
"Tuskaninny Battle Trumpet",
"Tuskaninny Personal Cannon",
"Tuskaninny Plant",
"Tuskaninny Raiders Helm",
"Twisting Vines",
"Two Rings Archmagus Plushie",
"Tyrannian Bori Morphing Potion",
"Tyrannian Flotsam Morphing Potion",
"Tyrannian Gnorbu Morphing Potion",
"Tyrannian JubJub Morphing Potion",
"Tyrannian Techo Plushie",
"Tyrannian Usuki Reject",
"Ugly Pinanna",
"Ultimate Dark Reflectorb",
"Ultimate Space Chronicles Set",
"Ultra Dual Shovel",
"Ultra Eyrie Eye Mask",
"Ultra Nova Pop",
"Ultra Supreme Kiko Walker",
"Under and Overripe Avocado Bombs",
"Uni Charm",
"Uni Healing Crown",
"Uni Hoof Magnet",
"Uni Horn Wand",
"Uni Myths",
"Unidentified Petpetpet",
"Unlockable Ice Treasure",
"Upside Down Island Acara Stamp",
"Usuki Artist Set",
"Usuki Buzzer Set",
"Usuki Defender",
"Usuki Dream Bike",
"Usuki Dream Jetski",
"Usuki Poetry Set",
"Usuki Rogue",
"Usukicon Year 9 Usuki",
"Utility Gloves",
"Vacumatic 9000",
"Valentines Boy Usuki",
"Valentines Girl Usuki",
"Vanity Doll",
"Veespa",
"Vegetarian Sloth Wrap",
"Vein Cabbage",
"Vengeful Scroll",
"Vernax",
"Vile Curse of Pestilence",
"Vile Scroll of Possession",
"Vira Bookmark",
"Vira Eraser",
"Vira Pencil Holder",
"Vira Ruler",
"Virtublaster 5000",
"Volcanic Pond",
"Volcano Crystal",
"Vullard",
"Waiting for Midnight",
"Waking the Draik",
"Warriors Might",
"Warriors Spatha",
"Water Acara Morphing Potion",
"Water Buzz Morphing Potion",
"Water Faerie Bubbles",
"Water Faerie Doll",
"Water Faerie Token",
"Water Flotsam Morphing Potion",
"Water Gnorbu Morphing Potion",
"Water Usul Morphing Potion",
"Well-Aged Hot Dog",
"Welsh Usuki Reject",
"Werewolf Usuki",
"What What What Stick",
"White Chia Morphing Potion",
"White Chomby Morphing Potion",
"White Draik Plushie",
"White Flotsam Morphing Potion",
"White Ixi Morphing Potion",
"White Ixi Plushie",
"White Linen Tunic",
"White Picket Fence",
"White Skeith Morphing Potion",
"White Wood Pergola",
"Wibreth Comb",
"Wiggly Glowing Drawer",
"Wilderness Usuki Set",
"Wing of Korbat",
"Winged Shoyru Amulet",
"Winged Shoyru Spear",
"Wobbly Turtum Toy",
"Wocky Battle Mallet",
"Wocky Slingshot",
"Wooden Kau Wand",
"Wooden Krawk Bow",
"Wooden Krawk Mallet",
"Wooden Krawk Shield",
"Wooden Krawk Staff",
"Wooden Meerca Mallet",
"Woodland Bori Morphing Potion",
"Woodland Brew",
"Woodland Eyrie Morphing Potion",
"Woodland Koi Morphing Potion",
"Woodland Lenny Morphing Potion",
"Woodland Mynci Morphing Potion",
"Woodland Pteri Morphing Potion",
"Woodland Skeith Morphing Potion",
"Woodland Tonu Morphing Potion",
"Woodland Wocky Morphing Potion",
"Woolypapith",
"Wormoeba",
"Wraith Draik Morphing Potion",
"Wraith Gelert Morphing Potion",
"Wraith Grundo Morphing Potion",
"Wraith Korbat Morphing Potion",
"Wraith Krawk Morphing Potion",
"Wraith Ogrin Morphing Potion",
"Wraith Pteri Morphing Potion",
"Wraith Scorchio Morphing Potion",
"Wraith Shoyru Morphing Potion",
"Wrawk the Merciless Plushie",
"Xantan Stamp",
"Xweetok Battle Batons",
"Xweetok Boots Of Speed",
"Year 8 Usuki",
"Year 9 Quiguki",
"Year 9 Usuki",
"Yellow Acara Morphing Potion",
"Yellow Avabot T-Shirt",
"Yellow Blumaroo Morphing Potion",
"Yellow Bori Morphing Potion",
"Yellow Buzz Morphing Potion",
"Yellow Buzzer T-Shirt",
"Yellow Chia Morphing Potion",
"Yellow Clockwork Grundo",
"Yellow Clockwork Lupe",
"Yellow Doughnutfruit",
"Yellow Draik Morphing Potion",
"Yellow Elephante Morphing Potion",
"Yellow Gelert Morphing Potion",
"Yellow Grarrl Morphing Potion",
"Yellow Grundo Morphing Potion",
"Yellow Jetsam Morphing Potion",
"Yellow Kacheek Morphing Potion",
"Yellow Kau Morphing Potion",
"Yellow Kiko Morphing Potion",
"Yellow Koi Morphing Potion",
"Yellow Kookith T-Shirt",
"Yellow Korbat Morphing Potion",
"Yellow Krawk Morphing Potion",
"Yellow Kyrii Morphing Potion",
"Yellow Lenny Morphing Potion",
"Yellow Lupe Morphing Potion",
"Yellow Moehog Morphing Potion",
"Yellow Moltenore T-Shirt",
"Yellow Mynci Morphing Potion",
"Yellow Nimmo Morphing Potion",
"Yellow Poogle Morphing Potion",
"Yellow Ramosan T-Shirt",
"Yellow Skeith Morphing Potion",
"Yellow Sunutek T-Shirt",
"Yellow Techo Morphing Potion",
"Yellow Usul Morphing Potion",
"Yellow Wocky Morphing Potion",
"Yellow Zafara Morphing Potion",
"Yellow Zebba T-Shirt",
"You Will Get Verrucas!",
"Youve Been Hexed!",
"Yurble Blocking Shield",
"Yurble Forest Blade",
"Yurble Forest Cloak",
"Yurble Forest Shield",
"Zafara Mystery Collection",
"Zebie",
"Zeenana Split",
"Zero-G Scout Pack",
"Zibblifruit",
"Zombie Buzz Morphing Potion",
"Zombie Draik Egg",
"Zombie Eyrie Morphing Potion",
"Zombie Korbat Morphing Potion",
"Zombie Mynci Morphing Potion",
"Zoomik",
"Zumagorn",
"Zytch"
 ]
};